### ISSUE TITLE
Enable reverse portrait?

### ISSUE THREAD

**Issue by RamKromberg** [scoutant/rpn#10]
Would be nice to flip the phone 180° when charging so the cable won't get in the way.

I believe it's done in https://github.com/scoutant/rpn/blob/master/app/src/main/AndroidManifest.xml#L14 by setting android:screenOrientation="portrait" to android:screenOrientation="sensorPortrait" but I haven't tested it.

**Comment by scoutant** [comment]
Absolutely. Done as mentioned. In release 1.3. In addition you'll find landscape modes.

**Comment by RamKromberg** [comment]
the release apk works well. thanks!
