### ISSUE TITLE
Incompatible with the popular Android devices

### ISSUE THREAD

**Issue by HiFromAjay** [scoutant/rpn#7]
Related to #6. The app is not available in the Play store of the popular Android devices currently in use such as Galaxy Grand Prime, J2, J1 Ace, and Oppo A37f. The devices support min SDK 22. However, the app supports min SDK 23.

**Comment by pklapperich** [comment]
Is this still true? I'm using this on Android 9 without problems.

**Comment by HiFromAjay** [comment]
Although not guaranteed, Android apps are generally forward compatible. In this case, the app supports min SDK 23 and your device supports min SDK 28 (Android 9). Therefore, the app is running on your device. However, the app will not work on the devices that have min SDK 22 or below (backward incompatibility).

**Comment by pklapperich** [comment]
The word minimum in there when describing the device is confusing. The highest SDK your device supports is SDK22; I understand now.

**Comment by scoutant** [comment]
And now release 1.2, with AndroidX refactoring, targets Android 7, 8, 9 and 10.
