### ISSUE TITLE
Needs stack manipulation.

### ISSUE THREAD

**Issue by bobpaul** [scoutant/rpn#8]
Rotate Up and Rotate Down functions would really round out this application.

**Rotate Up**
This takes the item from the top of the stack and places it on the bottom of the stack. Eg:
```
213
400
3
``` 
becomes
```
400
3
213
```

**Rotate Down**
The item from the bottom of the stack is relocated to the top of the stack. Eg:

```
213
400
3
``` 
becomes
```
3
213
400
```

`R↑` and `R↓` pair really nicely with swap and result in a fully functional stack. I like to use the top of the stack as "memory". This lets me compute multiple formulations on the same screen without the need to store results on a sheet of paper.

----

To free up space for the extra 2 buttons, we could do 2 of the following:

- shrink the enter button to so that a button will fit between `drop` and `Enter`. 
- completely remove `√`, which is superfluous as it's the same function as `0.5[xⁿ]`.
- completely remove`+/-`, as it's the same as `0[swap]-`

**Comment by scoutant** [comment]
Thanks for the suggestions. But I prefer to keep it very easy to use. Regards.
